//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_SanPhamTieuDung_.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNang
    {
        public int MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public Nullable<int> MaLoaiTaiKhoan { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
    
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
