//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_SanPhamTieuDung_.Net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SanPhamTieuDungEntities : DbContext
    {
        public SanPhamTieuDungEntities()
            : base("name=SanPhamTieuDungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<LoaiTaiKhoan> LoaiTaiKhoans { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhuongThucThanhToan> PhuongThucThanhToans { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
        public virtual DbSet<DanhMucSanPham> DanhMucSanPhams { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
    
        public virtual ObjectResult<GetAllProducts_Result> GetAllProducts(Nullable<int> madmsp)
        {
            var madmspParameter = madmsp.HasValue ?
                new ObjectParameter("madmsp", madmsp) :
                new ObjectParameter("madmsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProducts_Result>("GetAllProducts", madmspParameter);
        }
    
        public virtual ObjectResult<getProductKhuyenMai_Result> getProductKhuyenMai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductKhuyenMai_Result>("getProductKhuyenMai");
        }
    
        public virtual ObjectResult<Nullable<decimal>> DonHang_XacNhanDon(Nullable<int> mahoadon, Nullable<int> nhanVienThucHien)
        {
            var mahoadonParameter = mahoadon.HasValue ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(int));
    
            var nhanVienThucHienParameter = nhanVienThucHien.HasValue ?
                new ObjectParameter("nhanVienThucHien", nhanVienThucHien) :
                new ObjectParameter("nhanVienThucHien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("DonHang_XacNhanDon", mahoadonParameter, nhanVienThucHienParameter);
        }
    }
}
